=== olger/xmlbus/libxmlbus/data/wsaddr-testset/assertions/assertions.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY ws-addr-core "http://www.w3.org/TR/ws-addr-core/">
<!ENTITY ws-addr-soap "http://www.w3.org/TR/ws-addr-soap/">
<!ENTITY ws-addr-wsdl "http://www.w3.org/TR/ws-addr-soap/">

<!ELEMENT assertions (assertion+)>
<!ELEMENT assertion (text, note)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT text (#PCDATA)>

<!ATTLIST assertions
  xmlns CDATA "http://www.w3.org/2005/08/addressing/test-cases/assertions"
>

<!ATTLIST assertion
  xml:id CDATA #REQUIRED
  level (deprecated | informative | may | should | must) #REQUIRED
  doc CDATA #REQUIRED
  section CDATA #REQUIRED
>

=== olger/xmlbus/libxmlbus/data/wsaddr-testset/assertions/assertions.xml
<?xml version="1.0"?>
<!-- 
    Web Services Addressing Test Assertions
    $Date: 2005/09/29 17:01:55 $ 
-->

<!DOCTYPE assertions SYSTEM "./assertions.dtd">

<assertions xmlns="http://www.w3.org/2005/08/addressing/test-cases/assertions">
  <assertion xml:id="SOAP12-Feature-MEP" level="may" doc="&ws-addr-soap;"
    section="s12featuredesc">
    <text>[the SOAP 1.2 Addressing] feature may be used with any SOAP MEP.</text>
    <note>TBD: Need to expand to enumerate SOAP MEPs under test.</note>
  </assertion>

  <assertion xml:id="SOAP12-Properties" level="must" doc="&ws-addr-soap;"
    section="s12featuredesc">
    <text>A binding that supports [the SOAP 1.2 Addressing] feature MUST provide a means to transmit
      the properties [listed] and to reconstitute their values on receipt of a message.</text>
    <note>Not directly testable, enumerated below. Expect to split each property into 
	separate, multiple assertions for format, cadinality, etc.</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-Destination" level="must" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [destination]  property.</text>
    <note>Negative test cases for cardinatlity (1..1), non IRI format.</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-SourceEndpoint" level="may" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [source endpoint] property. [feature at risk]</text>
    <note>Test cases for cardinality (0..1).</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-ReplyEndpoint" level="may" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [reply endpoint] property.</text>
    <note>Test cases for cardinatlity (0..1).</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-FaultEndpoint" level="may" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [reply endpoint] property.</text>
    <note>Tests with FaultEndpoint which succeed and fail. Tests which fault, but for which
           FaultEndpoint is missing.  Test cases for cardinatlity (0..1).</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-Action" level="may" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [action] property.</text>
    <note>Negative tests with invalid IRI.
	   Test cases for cardinatlity (1..1).</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-MessageID" level="may" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [message id] property.</text>
    <note>Negative tests with invalid IRI.
	   Test cases with duplicated IRI values (results unlcear)?
	   Test cases for cardinatlity (0..1).</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-Relationship" level="may" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [relationship] property.</text>
    <note>Negative tests with invalid IRI values.
	   Test cases with addressing reply type IRI.
	   Test cases with unspecified message value IRI.
	</note>
  </assertion>

  <assertion xml:id="SOAP12-Property-ReferenceParameters" level="may" doc="&ws-addr-soap;"
    section="s12featureprops">
    <text>Corresponds to the abstract [reference parameters] property.</text>
    <note>Complex XML. Test cases for cardinatlity (0..unbounded).</note>
  </assertion>

  <assertion xml:id="SOAP12-Feature-MEP" level="may" doc="&ws-addr-soap;"
    section="s12featuredesc">
    <text>[extensibility of SOAP headers]</text>
    <note>I'm sure the schema alows for attribute extensibility, but is this explicity stated?</note>
  </assertion>

  <assertion xml:id="SOAP12-Feature-Action" level="must" doc="&ws-addr-soap;"
    section="s12featureinteractions">
    <text>If the http://www.w3.org/2003/05/soap/features/action/Action property of the SOAP Action
      feature has a value, then the value of [action] property of the SOAP 1.2 Addressing 1.0 feature 
      MUST be identical to it. Failure to have an
      identical value results in an Invalid Addressing Header fault.</text>
    <note>Easily testable.</note>
  </assertion>

  <assertion xml:id="SOAP12-Feature-Targeting" level="informative" doc="&ws-addr-soap;"
    section="s12featuredesc">
    <text>By default, the resulting header blocks are targeted at the ultimate recipient in the SOAP
      message path (note that extensions to WS-Addressing could be written to specify different
      targetting).</text>
    <note/>
  </assertion>

  <assertion xml:id="SOAP12-Module-Cardinality" level="must" doc="&ws-addr-soap;"
    section="s12moduledesc">
    <text>A message MUST NOT contain more than one wsa:To, wsa:ReplyTo, wsa:FaultTo, wsa:Action, or
      wsa:MessageID header targeted at a recipient. A recipient MUST generate a
      wsa:InvalidAddressingHeader fault if such a message is received.</text>
    <note>Easily testable.</note>
  </assertion>

  <assertion xml:id="SOAP12-Module-Targeting" level="informative" doc="&ws-addr-soap;"
    section="s12moduledesc">
      <text>The SOAP processing model dictates that message addressing properties targeted at an
            intermediary do not normally get relayed as message addressing properties when the
            message is forwarded along the message path.</text>
    <note/>
  </assertion>

  <assertion xml:id="SOAP12-Module-HeaderBehaviour" level="informative" doc="&ws-addr-soap;"
    section="s12moduledesc">
      <text>The specification for a SOAP header used as a reference property can override 
	{SOAP12-Module-MAP-Targeting}.</text>
    <note/>
  </assertion>

  <assertion xml:id="SOAP12-Module-SOAPRelay" level="informative" doc="&ws-addr-soap;"
    section="s12moduledesc">
      <text>The the soap:relay attribute can override {SOAP12-Module-MAP-Targeting}.</text>
    <note/>
  </assertion>

  <assertion xml:id="SOAP12-Module-Binding-MAPs" level="must" doc="&ws-addr-soap;"
    section="bindingrefp">
    <text>When a message is to be addressed to an endpoint, the XML Infoset representation of each
          message addressing property that has been assigned a value is inserted into the message as
          a SOAP header block subject to {SOAP12-Module-Binding-MAPs-Header}, {SOAP12-Module-isReferenceParameter}</text>
    <note>Whole raft of tests possible in this area, not least inclusion of Reference Properties
	which clash with those from other sources.</note>
  </assertion>

  <assertion xml:id="SOAP12-Module-Binding-MAPs-Header" level="must" doc="&ws-addr-soap;"
    section="bindingrefp">
      <text>The value, if any, of the [reference parameters] property is added to the SOAP
              message header: the element information item of each of the [reference parameters]
              (including all of its [children], [attributes] and [in-scope namespaces]) is added as
              a SOAP header block in the new message.</text>
      <note>Easily testible</note>
  </assertion>

  <assertion xml:id="SOAP12-Module-isReferenceParameter" level="must" doc="&ws-addr-soap;"
    section="bindingrefp">
      <text>Each header block added as a result of {SOAP12-Module-MAP-Binding} is annotated with a
              wsa:IsReferenceParameter attribute whose value is a valid xs:boolean representaion of 
	      true</text>
      <note>Easily testible</note>
  </assertion>

  <assertion xml:id="SOAP12-Module-Existing-isReferenceParameter" level="must" doc="&ws-addr-soap;"
    section="additionalinfoset">
      <text>[When processing] {SOAP12-Module-MAP-Binding]} any existing wsa:IsReferenceParameter 
	attribute on the header block is replaced.</text>
    <note>Test case with existing wsa:IsReferenceParameter in the EPR.</note>
  </assertion>

  <assertion xml:id="SOAP12-Module-Anonymous-Address-ReplyTo" level="may" doc="&ws-addr-soap;"
    section="soaphttp">
      <text>When [the anonymous URI] is specified as the address of the ReplyTo EPR,
          the underlying SOAP protocol binding provides a channel to the specified endpoint.
          Any underlying protocol binding supporting the SOAP request-response message 
          exchange pattern provides such a channel. For instance, the SOAP 1.2 
          HTTP binding puts the reply message in the HTTP response.
	</text>
    <note>Test cases for SOAP over HTTP with anonymous address in ReplyTo EPR.</note>
  </assertion>

  <assertion xml:id="SOAP12-Module-Anonymous-Address-FaultTo" level="may" doc="&ws-addr-soap;"
    section="soaphttp">
      <text>{SOAP-Module-Anonymous-Address-FaultTo} [applied to FaultTo EPR]</text>
    <note>Test cases for SOAP over HTTP with anonymous address in FaultTo EPR.</note>
  </assertion>

  <assertion xml:id="SOAP11-Module-HTTP-SOAPAction" level="must" doc="&ws-addr-soap;"
    section="soaphttp">
      <text>Use of the SOAPAction HTTP header is required when using the SOAP 1.1 HTTP binding.
	The value of the SOAPAction HTTP header MUST either be identical to the value of the
	wsa:Action header, or be empty. [snip]
	Failure to have an identical value, or an empty value for SOAPAction, results in an 
	Invalid Message Addressing Property fault.</text>
    <note>Positive test case for SOAP 1.1 over HTTP with identical and empty SOAPAction values.
    Negative test cases for SOAP 1.1 over HTTP with non-identical and empty SOAPAction values.</note>
  </assertion>

  <assertion xml:id="SOAP12-Security" level="may" doc="&ws-addr-soap;"
    section="securityconsiderations">
      <text>[...]</text>
      <note>Test cases composed with WS-Security.</note>
  </assertion>

  <assertion xml:id="SOAP12-Fault-RetryAfter" level="may" doc="&ws-addr-soap;"
    section="faultdetailelements">
      <text>[The RetryAfter] element (whose content is of type xs:unsignedLong) is a suggested minimum
                  duration in milliseconds to wait before retransmitting the message. Omission of this
